User's Guide
------------

This part of the documentation should give you an idea how to work with pycall.
It walks you through everything you need to know to develop applications with
pycall in a quick, simple manner.

.. toctree::

	foreword
	installation
	quickstart
	tutorial
	testing

API Reference
-------------

If you are looking for information on a specific function, class or method,
this part of the documentation is for you.

.. toctree::

	api

Additional Notes
----------------

Design notes, legal information and changelog are here for the interested.

.. toctree::

	design
	license
	changelog
